#ifndef MEMBERREGISTERDIALOG_H
#define MEMBERREGISTERDIALOG_H

#include <QDialog>
#include <QDate>

namespace Ui {
class MemberRegisterDialog;
}

class MemberRegisterDialog : public QDialog
{
    Q_OBJECT

public:
    explicit MemberRegisterDialog(QWidget *parent = nullptr);
    ~MemberRegisterDialog();

signals:
    void memberRegistered(QString phone, QString name, QDate birthday);

private slots:
    void onRegisterClicked();
    void onResetClicked();
    void onBackClicked();
    void onPhoneChanged(const QString &text); // 新增：手机号改变事件

private:
    Ui::MemberRegisterDialog *ui;
    bool nameAutoGenerated; // 标记姓名是否自动生成
};

#endif // MEMBERREGISTERDIALOG_H
